Description: Launch template for EC2 instances

# Use public Systems Manager Parameter
Parameters:
  UbuntuId:
    Type: String
    Default: ami-052efd3df9dad4825

# Use public Systems Manager Parameter
  WindowsId:
    Type: String
    Default: ami-03e42a81d67097502

Resources:
  LaunchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: mattgtemplate
      LaunchTemplateData:
        InstanceType: t2.large
        KeyName: mattgclikey
        SecurityGroupIds:
          - !ImportValue allowingresssecuritygroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: mattgltinstance2
              - Key: user
                Value: matthew.gable.labs2
              - Key: stelligent-u-lesson
                Value: 5.x
              - Key: stelligent-u-lab2
                Value: 5.x
  # EC2InstanceWindows:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     ImageId: !Ref WindowsId
  #     SubnetId: !ImportValue mattgpublicsubnet1
  #     LaunchTemplate: 
  #       LaunchTemplateId: !Ref LaunchTemplate1
  #       Version: 1
  EC2InstanceUbuntu:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref UbuntuId
      SubnetId: !ImportValue mattgpublicsubnet1
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate1
        Version: 1
  UbuntuElasticIP:
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
      InstanceId: !Ref EC2InstanceUbuntu

Outputs:
  UbuntuEIP:
    Description: The Elastic IP of the Ubuntu Instance
    Value: !Ref UbuntuElasticIP
    Export:
      Name: mattgubuntueip