Description: Launch template for EC2 instances

Resources:
  LaunchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: mattgtemplate
      LaunchTemplateData:
        InstanceType: t2.large
        KeyName: mattg
        SecurityGroupIds:
          - !ImportValue allowingresssecuritygroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: mattgltinstance
              - Key: user
                Value: matthew.gable.labs
              - Key: stelligent-u-lesson
                Value: 5.x
              - Key: stelligent-u-lab
                Value: 5.x
  EC2InstanceWindows:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dff35e6f6e21b962
      SubnetId: !ImportValue mattgpublicsubnet1
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate1
        Version: 1
  EC2InstanceUbuntu:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-052efd3df9dad4825
      SubnetId: !ImportValue mattgpublicsubnet1
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate1
        Version: 1