---
AWSTemplateFormatVersion: 2010-09-09

Description: 'mattg s3 bucket'

Parameters:
  BucketName:
    Type: String
    Description: 'The bucket'
    Default: "mattgDefaultBucketName"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Tags: 
      #   - Key: 'Name'
      #     Value: !Join ["-", [ !Ref "AWS::AccountId", !Ref BucketName]]
      BucketName: !Join ["-", [ !Ref "AWS::AccountId", !Ref BucketName]]

# Outputs:
#   AWSAccountId:
#    Value: !Ref 'AWS::AccountId'