---
AWSTemplateFormatVersion: 2010-09-09

Description: 'mattg s3 bucket'

Parameters:
  BucketName:
    Type: String
    Description: 'The bucket'
    Default: "mattgDefaultBucketName"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If ["BucketInPreferredRegion",  !Join ["-", [ !Ref "AWS::AccountId", !Ref BucketName]],  !Join ["-", [ !Ref "AWS::Region", !Ref BucketName]]]

Conditions:
  BucketInPreferredRegion: 
    !Equals [!Ref "AWS::Region", "us-west-1"]