---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: "mattgImportedPolicyUser"
      ManagedPolicyArns: 
        - !ImportValue "mattgstack-s3-arn"

