---
AWSTemplateFormatVersion: 2010-09-09

Description: 'mattg iam role'

Resources:
  MattIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Description: 'A reusable customer managed policy'
    Properties:
      PolicyName: inlinereadonlyeiam
      Roles:
       - !Ref MattGIAMRole
       - !Ref MattGIAMRole2
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "iam:Get*"
              - "iam:List*"
              - "iam:Generate*"
            Resource: "arn:aws:iam::*"
  MattIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - "*"
            Action:
              - "sts:AssumeRole"
      RoleName: MattGIAMRole
  MattIAMRole2:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - "*"
            Action:
              - "sts:AssumeRole"
      RoleName: MattGIAMRole2
