---
AWSTemplateFormatVersion: 2010-09-09

Description: 'mattg iam role'

Resources:
  MattIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - "*"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/IAMReadOnlyAccess"
      # Policies:
      #   - PolicyName: inlinereadonlyeiam
      #     PolicyDocument:
      #       Version: "2012-10-17"
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - "iam::Get*"
      #             - "iam:List*"
      #             - "iam:Generate*"
      #           Resource: ""
