---
AWSTemplateFormatVersion: 2010-09-09

Description: 'mattg iam role'

Resources:
  MattIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS:
                - "arn:aws:iam::324320755747:user/matthew.gable.labs"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/IAMReadOnlyAccess"
      RoleName: MattGIAMRole